name: Android CI

on:
  push:
    branches: [ master ]

jobs:

  build-storybook:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: install node_modules
        run: yarn install
      - name: Build with Gradle
        run: cd ./android && ENTRY_FILE=storybook/index.js ./gradlew assembleStorybookRelease
      - name: upload storybook artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_STORYBOOK_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testgroup
          file: android/app/build/outputs/apk/storybookRelease/app-storybookRelease.apk
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-storybookRelease.apk
          path: android/app/build/outputs/apk/storybookRelease/app-storybookRelease.apk

