name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: install node_modules
      run: yarn install
    - name: Build with Gradle
      run: cd ./android && ./gradlew assembleRelease
    - name: Upload Artifact Apk
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: android/app/build/outputs/apk/release/
    - name: Upload Artifact JS bundle
      uses: actions/upload-artifact@v2
      with:
        name: index.android.bundle
        path: android/app/build/generated/assets/react/release/
    - name: Upload Artifact JS sourcemap
      uses: actions/upload-artifact@v2
      with:
        name: index.android.bundle.map
        path: android/app/build/generated/sourcemap/react/release/

  build-storybook:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: install node_modules
        run: yarn install
      - name: Build with Gradle
        run: cd ./android && ENTRY_FILE=storybook/index.js ./gradlew assembleStorybookRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-storybookRelease.apk
          path: android/app/build/outputs/apk/storybookRelease/

