name: Android CI

on:
  push:
    branches: [ master ]

jobs:
  build-release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: install node_modules
      run: yarn install
    - name: Decode production config
      env:
        PRODUCTION_CONFIG: ${{ secrets.PRODUCTION_CONFIG }}
      run: echo $PRODUCTION_CONFIG | base64 -d > .env.production
    - name: Decode production keystore properties
      env:
        PRODUCTION_KEYSTORE_PROPERTIES: ${{ secrets.PRODUCTION_KEYSTORE_PROPERTIES }}
      run: echo $PRODUCTION_KEYSTORE_PROPERTIES | base64 -d > ./android/production.keystore.properties
    - name: Decode production keystore
      env:
        PRODUCTION_KEYSTORE: ${{ secrets.PRODUCTION_KEYSTORE }}
      run: echo $PRODUCTION_KEYSTORE | base64 -d > ./android/app/production.keystore
    - name: Build with Gradle
      run: cd ./android && BABEL_ENV=production ./gradlew assembleRelease
    - name: Upload Artifact Apk
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: android/app/build/outputs/apk/release/app-release.apk
    - name: Upload Artifact JS bundle
      uses: actions/upload-artifact@v2
      with:
        name: index.android.bundle
        path: android/app/build/generated/assets/react/release/
    - name: Upload Artifact JS sourcemap
      uses: actions/upload-artifact@v2
      with:
        name: index.android.bundle.map
        path: android/app/build/generated/sourcemaps/react/release/
